//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.evidente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.datacredito.com.co/services/ServicioIdentificacion", ConfigurationName="evidente.ServicioIdentificacionImpl")]
    public interface ServicioIdentificacionImpl {
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarTiposAlerta();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarTiposAlertaAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarAlertas();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarAlertasAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarEstadisticasDetalladas();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarEstadisticasDetalladasAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametrizacionesCompletas();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametrizacionesCompletasAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametrizaciones();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametrizacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void validar();
        
        [System.ServiceModel.OperationContractAttribute()]
        void validarAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void preguntas();
        
        [System.ServiceModel.OperationContractAttribute()]
        void preguntasAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void verificar();
        
        [System.ServiceModel.OperationContractAttribute()]
        void verificarAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarCodigosValidacion();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarCodigosValidacionAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarCodigosPreguntas();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarCodigosPreguntasAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametro();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametroAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametroParametrizaciones();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametroParametrizacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametroParametrizaciones1();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametroParametrizaciones1Async();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametrizacion();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarParametrizacionAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarUltimoResultado();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarUltimoResultadoAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarSistemaAlertas();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarSistemaAlertasAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarListaEstadisticasGeneradas();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarListaEstadisticasGeneradasAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarListaEstadisticasEncuestasGeneradas();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarListaEstadisticasEncuestasGeneradasAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void adicionarRespuestaCuestionario();
        
        [System.ServiceModel.OperationContractAttribute()]
        void adicionarRespuestaCuestionarioAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarEstadisticasEncuestasDetalladas();
        
        [System.ServiceModel.OperationContractAttribute()]
        void consultarEstadisticasEncuestasDetalladasAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void generarCodigoOTP();
        
        [System.ServiceModel.OperationContractAttribute()]
        void generarCodigoOTPAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void verificarCodigoOTP();
        
        [System.ServiceModel.OperationContractAttribute()]
        void verificarCodigoOTPAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void iniciarTransaccionOTP();
        
        [System.ServiceModel.OperationContractAttribute()]
        void iniciarTransaccionOTPAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioIdentificacionImplChannel : WebApplication1.evidente.ServicioIdentificacionImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioIdentificacionImplClient : System.ServiceModel.ClientBase<WebApplication1.evidente.ServicioIdentificacionImpl>, WebApplication1.evidente.ServicioIdentificacionImpl {
        
        public ServicioIdentificacionImplClient() {
        }
        
        public ServicioIdentificacionImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioIdentificacionImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioIdentificacionImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioIdentificacionImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void consultarTiposAlerta() {
            base.Channel.consultarTiposAlerta();
        }
        
        public void consultarTiposAlertaAsync() {
            base.Channel.consultarTiposAlertaAsync();
        }
        
        public void consultarAlertas() {
            base.Channel.consultarAlertas();
        }
        
        public void consultarAlertasAsync() {
            base.Channel.consultarAlertasAsync();
        }
        
        public void consultarEstadisticasDetalladas() {
            base.Channel.consultarEstadisticasDetalladas();
        }
        
        public void consultarEstadisticasDetalladasAsync() {
            base.Channel.consultarEstadisticasDetalladasAsync();
        }
        
        public void consultarParametrizacionesCompletas() {
            base.Channel.consultarParametrizacionesCompletas();
        }
        
        public void consultarParametrizacionesCompletasAsync() {
            base.Channel.consultarParametrizacionesCompletasAsync();
        }
        
        public void consultarParametrizaciones() {
            base.Channel.consultarParametrizaciones();
        }
        
        public void consultarParametrizacionesAsync() {
            base.Channel.consultarParametrizacionesAsync();
        }
        
        public void validar() {
            base.Channel.validar();
        }
        
        public void validarAsync() {
            base.Channel.validarAsync();
        }
        
        public void preguntas() {
            base.Channel.preguntas();
        }
        
        public void preguntasAsync() {
            base.Channel.preguntasAsync();
        }
        
        public void verificar() {
            base.Channel.verificar();
        }
        
        public void verificarAsync() {
            base.Channel.verificarAsync();
        }
        
        public void consultarCodigosValidacion() {
            base.Channel.consultarCodigosValidacion();
        }
        
        public void consultarCodigosValidacionAsync() {
            base.Channel.consultarCodigosValidacionAsync();
        }
        
        public void consultarCodigosPreguntas() {
            base.Channel.consultarCodigosPreguntas();
        }
        
        public void consultarCodigosPreguntasAsync() {
            base.Channel.consultarCodigosPreguntasAsync();
        }
        
        public void consultarParametro() {
            base.Channel.consultarParametro();
        }
        
        public void consultarParametroAsync() {
            base.Channel.consultarParametroAsync();
        }
        
        public void consultarParametroParametrizaciones() {
            base.Channel.consultarParametroParametrizaciones();
        }
        
        public void consultarParametroParametrizacionesAsync() {
            base.Channel.consultarParametroParametrizacionesAsync();
        }
        
        public void consultarParametroParametrizaciones1() {
            base.Channel.consultarParametroParametrizaciones1();
        }
        
        public void consultarParametroParametrizaciones1Async() {
            base.Channel.consultarParametroParametrizaciones1Async();
        }
        
        public void consultarParametrizacion() {
            base.Channel.consultarParametrizacion();
        }
        
        public void consultarParametrizacionAsync() {
            base.Channel.consultarParametrizacionAsync();
        }
        
        public void consultarUltimoResultado() {
            base.Channel.consultarUltimoResultado();
        }
        
        public void consultarUltimoResultadoAsync() {
            base.Channel.consultarUltimoResultadoAsync();
        }
        
        public void consultarSistemaAlertas() {
            base.Channel.consultarSistemaAlertas();
        }
        
        public void consultarSistemaAlertasAsync() {
            base.Channel.consultarSistemaAlertasAsync();
        }
        
        public void consultarListaEstadisticasGeneradas() {
            base.Channel.consultarListaEstadisticasGeneradas();
        }
        
        public void consultarListaEstadisticasGeneradasAsync() {
            base.Channel.consultarListaEstadisticasGeneradasAsync();
        }
        
        public void consultarListaEstadisticasEncuestasGeneradas() {
            base.Channel.consultarListaEstadisticasEncuestasGeneradas();
        }
        
        public void consultarListaEstadisticasEncuestasGeneradasAsync() {
            base.Channel.consultarListaEstadisticasEncuestasGeneradasAsync();
        }
        
        public void adicionarRespuestaCuestionario() {
            base.Channel.adicionarRespuestaCuestionario();
        }
        
        public void adicionarRespuestaCuestionarioAsync() {
            base.Channel.adicionarRespuestaCuestionarioAsync();
        }
        
        public void consultarEstadisticasEncuestasDetalladas() {
            base.Channel.consultarEstadisticasEncuestasDetalladas();
        }
        
        public void consultarEstadisticasEncuestasDetalladasAsync() {
            base.Channel.consultarEstadisticasEncuestasDetalladasAsync();
        }
        
        public void generarCodigoOTP() {
            base.Channel.generarCodigoOTP();
        }
        
        public void generarCodigoOTPAsync() {
            base.Channel.generarCodigoOTPAsync();
        }
        
        public void verificarCodigoOTP() {
            base.Channel.verificarCodigoOTP();
        }
        
        public void verificarCodigoOTPAsync() {
            base.Channel.verificarCodigoOTPAsync();
        }
        
        public void iniciarTransaccionOTP() {
            base.Channel.iniciarTransaccionOTP();
        }
        
        public void iniciarTransaccionOTPAsync() {
            base.Channel.iniciarTransaccionOTPAsync();
        }
    }
}
